version: '2'

# Define the services/containers to be run
services:
  smarati_be: #name of your service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - mongo_database # link this service to the database service
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo_database
      
  mongo_database: # name of the service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017"