version: '2'
 
# Data volume for Mongo
volumes:
  mongostorage:
 
# Services (Docker containers)
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:3.2
    volumes: 
      - mongostorage:/data/db
    ports:
      - "27017:27017"
